###############################################################################
# Licensed Materials - Property of IBM.
# Copyright IBM Corporation 2017. All Rights Reserved.
# U.S. Government Users Restricted Rights - Use, duplication or disclosure
# restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Contributors:
#  IBM Corporation - initial API and implementation
###############################################################################
# barFile: "http://9.19.34.117/storage/CASE/refarch-privatecloud/iibApp.bar"
barFile: "/iibApp.bar"
iib:
  nodeName: NODE
  server: default
mq:
  qmgrName: QM1
image:
  repository: master.cfc:8500/default/iib10009
  tag: v0.0.1
service:
  type: NodePort
  nodePort:
    webui: 30414
    serverlistener: 30780
    nodelistener: 30708
    mqchannel: 30141
    mqwebui: 30443
